-- HR 僅能管理員工模組
--
-- 執行時機：建立 thestar schema 並匯入原始資料後。
-- 此 migration 可重複執行，不依賴固定的 ROLE_ID / EMPLOYEE_ID。

START TRANSACTION;

INSERT INTO ROLE (ROLE_NAME, ROLE_CODE, STATUS)
VALUES ('人資管理員', 'ROLE_HR', 1)
ON DUPLICATE KEY UPDATE
    ROLE_NAME = '人資管理員',
    STATUS = 1;

-- HR 帳號只保留 ROLE_HR，避免仍持有 SUPER_ADMIN 或其他模組角色。
DELETE er
FROM EMPLOYEE_ROLE er
JOIN EMPLOYEE e ON e.EMPLOYEE_ID = er.EMPLOYEE_ID
WHERE e.EMPLOYEE_MAIL = 'hr.lin@hotel.com';

INSERT INTO EMPLOYEE_ROLE (EMPLOYEE_ID, ROLE_ID)
SELECT e.EMPLOYEE_ID, r.ROLE_ID
FROM EMPLOYEE e
JOIN ROLE r ON r.ROLE_CODE = 'ROLE_HR'
WHERE e.EMPLOYEE_MAIL = 'hr.lin@hotel.com';

COMMIT;

-- 驗證結果：應只回傳一筆 ROLE_HR。
SELECT e.EMPLOYEE_MAIL, r.ROLE_NAME, r.ROLE_CODE, r.STATUS
FROM EMPLOYEE e
JOIN EMPLOYEE_ROLE er ON er.EMPLOYEE_ID = e.EMPLOYEE_ID
JOIN ROLE r ON r.ROLE_ID = er.ROLE_ID
WHERE e.EMPLOYEE_MAIL = 'hr.lin@hotel.com';
